version: '3.8'

services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    environment:
      POSTGRES_DB: hrms_staging
      POSTGRES_USER: hrms_staging
      POSTGRES_PASSWORD: ${STAGING_DB_PASSWORD}

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - DATABASE_URL=postgresql://hrms_staging:${STAGING_DB_PASSWORD}@postgres:5432/hrms_staging
      - ENVIRONMENT=staging
      - LOG_LEVEL=DEBUG
    ports:
      - "8080:8000"

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_ENVIRONMENT=staging
    ports:
      - "3080:80"