global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "hrms_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'hrms-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  - job_name: 'hrms-ai-services'
    static_configs:
      - targets: ['ai-services:8001']
    metrics_path: '/metrics'
    scrape_interval: 60s
    
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']